INSERT INTO "MasterModule" ("MasterModuleCode", "MasterModuleName", "MasterModuleCreatedAt", "MasterModuleUpdatedAt", "MasterModuleDeletedAt", "MasterModuleCreatedBy", "MasterModuleUpdatedBy", "MasterModuleDeletedBy") 
VALUES 
('JB', 'JABATAN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1, 1, NULL),
('EM', 'Employee', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP, NULL, 1, 1, NULL),
('MD', 'MODUL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1, 1, NULL),
('AS', 'ASET', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1, 1, NULL),
('HA', 'HAKAKSES', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1, 1, NULL),
('TA', 'TIMASET', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1, 1, NULL),
('US', 'USER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1, 1, NULL);
