INSERT INTO "Permission" ("PermissionModuleId", "PermissionRoleId", "PermissionCreatedAt", "PermissionUpdatedAt", "PermissionDeletedAt", "PermissionCreatedBy", "PermissionUpdatedBy", "PermissionDeletedBy") 
VALUES 
(1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1, 1, NULL),
(2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1, 1, NULL),
(3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1, 1, NULL),
(4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1, 1, NULL),
(5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1, 1, NULL),
(6, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1, 1, NULL);