INSERT INTO "MasterUnit" ("MasterUnitName", "MasterUnitCode", "MasterUnitCreatedAt", "MasterUnitUpdatedAt", "MasterUnitDeletedAt", "MasterUnitCreatedBy", "MasterUnitUpdatedBy", "MasterUnitDeletedBy", "MasterUnitInitial") 
VALUES 
('SEKRETARIAT', 'ST', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 3, 3, NULL, 'SEKRE'),
('APLIKASI DAN INFORMATIKA', 'AP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 3, 3, NULL, 'APTIKA'),
('PERSANDIAN KEAMANAN DAN INFORMASI', 'KSI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 3, 3, NULL, 'SANDIKAMI'),
('E-GOVERMENT', 'EGV', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 3, 3, NULL, 'EGOV'),
('STATISTIKA', 'STS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 3, 3, NULL, 'STATISTIK'),
('INFORMASI KOMUNIKASI PUBLIK', 'IKP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 3, 3, NULL, 'INKOP'),
('UNIT PELAYANAN TEKNIS DAERAH', 'UPTD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 3, 3, NULL, 'UPTEDE');
