INSERT INTO "MasterUnit" ("MasterUnitName", "MasterUnitCode", "MasterUnitInitial","MasterUnitCreatedAt", "MasterUnitUpdatedAt", "MasterUnitDeletedAt", "MasterUnitCreatedBy", "MasterUnitUpdatedBy", "MasterUnitDeletedBy") 
VALUES 
('SEKRETARIAT', 'ST', 'SEKRE',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 3, 3, NULL),
('APLIKASI DAN INFORMATIKA', 'AP', 'APTIKA',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 3, 3, NULL),
('PERSANDIAN KEAMANAN DAN INFORMASI', 'KSI','SANDIKAMI',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 3, 3, NULL),
('E-GOVERMENT', 'EGV', 'EGOV',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 3, 3, NULL),
('STATISTIKA', 'STS','STATISTIK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 3, 3, NULL),
('INFORMASI KOMUNIKASI PUBLIK', 'IKP', 'INKOP',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 3, 3, NULL),
('UNIT PELAYANAN TEKNIS DAERAH', 'UPTD', 'UPTEDE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 3, 3, NULL);
