INSERT INTO "MasterUnit" ("MasterUnitId", "MasterUnitName", "MasterUnitCode", "MasterUnitCreatedAt", "MasterUnitUpdatedAt", "MasterUnitDeletedAt", "MasterUnitCreatedBy", "MasterUnitUpdatedBy", "MasterUnitDeletedBy", "MasterUnitInitial") 
VALUES 
(1, 'SEKRETARIAT', 'ST', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 3, 3, NULL, 'SEKRE'),
(2, 'APLIKASI DAN INFORMATIKA', 'AP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 3, 3, NULL, 'APTIKA'),
(3, 'PERSANDIAN KEAMANAN DAN INFORMASI', 'KSI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 3, 3, NULL, 'SANDIKAMI'),
(4, 'E-GOVERMENT', 'EGV', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 3, 3, NULL, 'EGOV'),
(5, 'STATISTIKA', 'STS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 3, 3, NULL, 'STATISTIK'),
(6, 'INFORMASI KOMUNIKASI PUBLIK', 'IKP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 3, 3, NULL, 'INKOP'),
(7, 'UNIT PELAYANAN TEKNIS DAERAH', 'UPTD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 3, 3, NULL, 'UPTEDE');
